
export const list = [
    {
        id:"1",
        img_source:"./Havana.jpg",
        title:"Havana",
        artist:"Camilla Cabello",
        likes:"6k",
        shares:"2k",
        comments:"1.1k",
        downloads:"1k"
    },
    {
        id:"2",
        img_source:"./Havana.jpg",
        title:"Havana",
        artist:"Camilla",
        likes:"6k",
        shares:"2k",
        comments:"1.1k",
        downloads:"1k"
    },
    {
        id:"3",
        img_source:"./Havana.jpg",
        title:"Havana",
        artist:"Camilla",
        likes:"6k",
        shares:"2k",
        comments:"1.1k",
        downloads:"1k"
    },
    {
        id:"4",
        img_source:"./Havana.jpg",
        title:"Havana",
        artist:"Camilla",
        likes:"6k",
        shares:"2k",
        comments:"1.1k",
        downloads:"1k"
    },
    {
        id:"5",
        img_source:"./Havana.jpg",
        title:"Havana",
        artist:"Camilla",
        likes:"6k",
        shares:"2k",
        comments:"1.1k",
        downloads:"1k"
    },
    {
        id:"6",
        img_source:"./Havana.jpg",
        title:"Havana",
        artist:"Camilla",
        likes:"6k",
        shares:"2k",
        comments:"1.1k",
        downloads:"1k"
    },
    {
        id:"7",
        img_source:"./Havana.jpg",
        title:"Havana",
        artist:"Camilla",
        likes:"6k",
        shares:"2k",
        comments:"1.1k",
        downloads:"1k"
    },
    {
        id:"8",
        img_source:"./Havana.jpg",
        title:"Havana",
        artist:"Camilla",
        likes:"6k",
        shares:"2k",
        comments:"1.1k",
        downloads:"1k"
    },
    {
        id:"9",
        img_source:"./Havana.jpg",
        title:"Havana",
        artist:"Camilla",
        likes:"6k",
        shares:"2k",
        comments:"1.1k",
        downloads:"1k"
    },
]